### ISSUE TITLE
Frequent spurious failures from  `test_rerun_timed_fws`

### ISSUE THREAD

**Issue by jakirkham** [materialsproject/fireworks#100]
I have seen this test fail often and suspect there is something wrong with the test itself (particularly as it is a timed test). Here is an example of it failing when I had only made changes to docs and docstrings ( https://travis-ci.org/materialsproject/fireworks/builds/60772474 ).

    ======================================================================
    FAIL: test_rerun_timed_fws (fireworks.core.tests.test_launchpad.WorkflowFireworkStatesTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/materialsproject/fireworks/fireworks/core/tests/test_launchpad.py", line 710, in test_rerun_timed_fws
        self.assertEqual(fw_state, fw_cache_state)
    nose.proxy.AssertionError: 'RUNNING' != 'READY'
    - RUNNING
    + READY

**Comment by computron** [comment]
Ok, I am assigning this to @mbkumar who wrote and is in charge of this test

**Comment by jakirkham** [comment]
Glad to hear someone will take a closer look. Thanks.
