### ISSUE TITLE
Accessing WF details from run_task

### ISSUE THREAD

**Issue by gpetretto** [materialsproject/fireworks#117]
I am facing the need of having detailed information about the whole workflow during the execution of a Task. In this case it is limited to simple tasks that will make a cleanup or storing of data from all the FWs launched during the WF, but I think that it could be generally useful to have the possibility of accessing detailed information about the workflow at the run_task level. 
At the moment, it is possible to do that by reading the FW id from the FW.json file and instantiating a LaunchPad with the autoload function to call the DB. However, there is a potential flaw in this approach, since the launchpad can be passed as an option to the q/m/rlaunch commands and there is no way to know that inside the Task. 
There could probably be some workaround, but I would prefer to add a cleaner way of accessing those data. I can think of two different ways of doing that and I would like to have a feedback.
1) one way would be to make an instance of the launchpad available, along with current FW and launch ids. This would be enough to extract all sort of information from the database, that can be accessed lazily. This will give the user the control to get exactly what he needs, but it will not be available for offline mode.
2) alternatively, it would be possible to get the information about the workflow when starting the FW and copy them in the fw_spec. This option could be turned on at the FW level with a keyword in the spec or with a general configuration parameter. The keyword can be used to specify the level of detail of the information that will be put in the spec (i.e. just the data of the workflow, or all the datails of the FWs, or even all the launches). 

Thanks

**Comment by computron** [comment]
Hi Guido,

As we discussed on the phone, there are some reasons why I'd like to avoid encouraging using the launchpad during the run - in particular, it is one way to break the convention of "fw_spec uniquely determines the inputs and the job to run, and therefore uniquely defines the output", i.e. which is used in duplicate checking.

That said, a few ideas include:

* easier ways to pass the run directory between jobs, including fw_id, fw_name, and launch_dir. I will work on this and it should address your issue.
* giving a FireTask access to "fw_id" and "launchpad" variables, which are set by the rocket before running "run_task()". I'm not really in favor of doing this unless it proves really necessary, so let's table this one.

**Comment by computron** [comment]
I think this issue should be solved in FWS 1.1.3

* easier way to pass run directory using _pass_job_info reserved spec key
* giving access to launchpad and fw_id using _add_launchpad_and_fw_id reserved spec key

Please reopen if you are still unable to make things work.
