### ISSUE TITLE
subprocess stdout and stderr bytes handling in python 3.*

### ISSUE THREAD

**Issue by felipeZ** [materialsproject/fireworks#137]
the `subprocess` module in python 3 returns a *byte sequence* for the stdout and stderr. The problem is that the function `_parse_jobid` and `_parse_njobs` from the ``common_adapter.py`` module, treat the output like a **str** because that is the standard for python 2 but for python 3 those functions fail when they receive an  array of bytes for input:
````python
 return len(output_str.split('\n'))-1
TypeError: a bytes-like object is required, not 'str'
````

**Comment by computron** [comment]
Hi Felipe

Thanks for the heads up. I pushed a patch via 7b72826f1bab065cd7853470cf48d4d0bfbd793a

I am going to close this for now, but if you can help confirm that it works, it would be very helpful. Note that the change is already on the latest Github for FWS but won't be on PyPI / pip until about Friday when I release a new version.
