### ISSUE TITLE
The 'QUEUEADAPTER_LOC' is 'None' in Fireworks.

### ISSUE THREAD

**Issue by specter119** [materialsproject/fireworks#145]
I works with Fireworks 1.2.7 with MPenv 0.1(sjtu branch) and Python 2.7.11.
when I type the following codes in python:

```python
from fireworks.fw_config import QUEUEADAPTER_LOC, CONFIG_FILE_DIR, FWORKER_LOC, LAUNCHPAD_LOC
print QUEUEADAPTER_LOC,'\n', CONFIG_FILE_DIR,'\n', FWORKER_LOC,'\n', LAUNCHPAD_LOC
```

I saw these:

```sh
None
$HOME/<ENV_NAME>/config/config_SjtuPi
$HOME/<ENV_NAME>/config/config_SjtuPi/my_fworker.yaml
$HOME/<ENV_NAME>/config/config_SjtuPi/my_launchpad.yaml
```

I found the relevant codes in [fireworks/fireworks/scripts/qlaunch_run.py](https://github.com/materialsproject/fireworks/blob/master/fireworks/scripts/qlaunch_run.py)
line 35-38 is to source the `queueadapter_file` as `my_qadapater.yaml`
but the line 104 set the default `QUEUEADAPTER_LOC` to `my_queueadapater.yaml`(which doesn't exist)
> what i mean is in the line 143-159 of [fireworks/fireworks/fw_config.py](https://github.com/materialsproject/fireworks/blob/master/fireworks/fw_config.py)

**I don't know whether the `my_qadapater.yaml` will work for command `qlaunch`?** Now, I just make a soft link `my_queueadapter.yaml -> my_qadapter.yaml`, this will help the 'QUEUEADAPTER_LOC' print normally.

**Comment by computron** [comment]
I am confused by your question. In all places, FireWorks defaults to "my_qadapter.yaml". If you are using the defaults, please make sure the name of your queue adapter file is "my_qadapter.yaml". You can name it something else, but then you need to change the FW Config appropriately in "FW_config.yaml".

Note that there was one comment (not code) where it mentioned the spelling "my_queueadapter.yaml", but it was only a comment. I have fixed that comment in 5b6439dd92482b84df0066f80395d17c5e0d2ad7.

Perhaps this resolves your issue? Just use "my_qadapter.yaml" as the file name is the easiest solution. Also, please note that in your original question mis-spelled this several times, so please take care in the spelling.

If you are having some problems related to MPEnv, I would suggest the MP google group:
https://groups.google.com/forum/#!forum/matproj-develop

At this point I do not see any other issue in FWS so I am closing the issue.

**Comment by specter119** [comment]
Sorry for my mis-spelled, I will check my question more carefully.
In lines 143~159 of  [fireworks/fireworks/fw_config.py](https://github.com/materialsproject/fireworks/blob/master/fireworks/fw_config.py)
```python
    for k in ["LAUNCHPAD_LOC", "FWORKER_LOC", "QUEUEADAPTER_LOC"]:
        if globals().get(k, None) is None:
            fname = "my_{}.yaml".format(k.split("_")[0].lower())
            m_paths = []
            if os.path.realpath(CONFIG_FILE_DIR) not in test_paths:
                test_paths.insert(0, CONFIG_FILE_DIR)
            for p in test_paths:
                fp = os.path.join(p, fname)
                if os.path.exists(fp) and fp not in m_paths:
                    m_paths.append(fp)

            if len(m_paths) > 1:
                print("Found many potential paths for {}: {}\nChoosing as default: {}"
                      .format(k, m_paths, m_paths[0]))

            if len(m_paths) > 0:
                globals()[k] = m_paths[0]
```
I think the value of "QUEUEADAPTER_LOC" should be `my_queueadapter.yaml`(if exist)
and in 106 of  [fireworks/fireworks/scripts/qlaunch_run.py](https://github.com/materialsproject/fireworks/blob/master/fireworks/scripts/qlaunch_run.py)

```python
parser.add_argument('-q', '--queueadapter_file', help='path to queueadapter file',
                        default=QUEUEADAPTER_LOC)
```

What is the default queueadapter file for command `qlaunch`? I find the 'walltime' in 'my_qadapter.yaml' useless.

**Comment by computron** [comment]
Ok - I see what you mean about the code looking for my_queueadapter.yaml. Somehow this issue never came up before. I pushed a patch via d781f2521a9c316f3f0ef991c6277285a3e5084e. I will also push a new pip version soon, e.g. Friday.

The code should now look for my_qadapter.yaml in the order of:
1) Config file location (see tutorials on how to set the fw config). This is the method that I use.
2) Current working directory
3)  $HOME/.fireworks directory

If you have your my_qadapter.yaml file in one of those directories, it should be detected.

>>  I find the 'walltime' in 'my_qadapter.yaml' useless.

What queue adapter are you using? I took a quick look and it looks like walltime is a valid parameter in all the queue adapter templates except SGE (which I nor my collaborators ever use). Perhaps you can quickly modify the SGE template to be more comprehensive and push back the changes, which is located in:
fireworks/fireworks/user_objects/queue_adapters/SGE_template.txt
