### ISSUE TITLE
Mechanism for using config directory for python defaults?

### ISSUE THREAD

**Issue by dotsdl** [materialsproject/fireworks#146]
Is there a mechanism for using configurations one might have in ``~./fireworks`` automatically when doing things like

```python

import fireworks

launchpad = fireworks.LaunchPad()

```
instead of having to put in the hostname, database name, username, password for a non-local MongoDB? I know that using ``lpad`` from the command line automatically uses these configurations, but if there's a reasonable way of telling ``fireworks.LaunchPad`` to do the same thing that would be awesome.

**Comment by computron** [comment]
try LaunchPad.auto_load()

p.s. - if follow up or further questions are needed, can you submit to the Google group?
https://groups.google.com/forum/#!forum/fireworkflows

**Comment by dotsdl** [comment]
Thanks! I'll use the mailing list for future questions.
