### ISSUE TITLE
Fireworks fail on systems without journalling.

### ISSUE THREAD

**Issue by shyuep** [materialsproject/fireworks#184]
Fireworks seem to initialize MongoClient with the j=True by default. But this causes an exception

pymongo.errors.OperationFailure: cannot use 'j' option when a host does not have journaling enabled

when working with new pymongo and db without journalling, e.g., on CircleCI.

Fireworks really shouldn't be setting such parameters and leave it to the end user to set this up properly.

**Comment by computron** [comment]
ok closed via b8ea8970c2daf5104f2e8a920a61ecbd53eefb32

**Comment by shyuep** [comment]
can release new version?

**Comment by computron** [comment]
I need to investigate the Travis failure with the new commits before releasing a new version.

https://travis-ci.org/materialsproject/fireworks

Probably can't do this today
