### ISSUE TITLE
Urgent feature request: Dynamically set qadapter variables

### ISSUE THREAD

**Issue by shyuep** [materialsproject/fireworks#191]
There are certain types of jobs where the number of nodes need to vary based on the actual calculation. A prime example is NEB, where number of nodes is equal to number of images usually. 

Right now, the FW # of nodes is hard-coded in the qadapter.yaml. While we can create multiple qadapters to cater to different number of node runs, this is extremely cumbersome to manage.

We need a way for qlaunch to dynamically set certain variables based on job type.

Note that this applies only for non-reservation mode, where it is one specific job per launch. 

@HanmeiTang pls provide more info as needed.

**Comment by computron** [comment]
Not sure I understand.

If it is one specific job per launch, then you can use reservation mode and then you can use the _qadapter variable to set specific queue parameters for specific jobs. This is already implemented for some time. You just need to make sure you run in reservation mode and set queue parameters in the FW spec.

If you need it to work in non-reservation mode (e.g., if you need to pack multiple jobs into a single queue submission) then it is not possible.

@HanmeiTang Maybe you can clarify a bit more?

Anubhav

**Comment by shyuep** [comment]
Ah yes. I forgot about the qadapter fw settings.

@hanmeitang, pls use that.
