### ISSUE TITLE
Need to add `matplotlib` to reqs for flask app plotting

### ISSUE THREAD

**Issue by dwinston** [materialsproject/fireworks#230]
I don't know if you'd prefer to add to `install_requires` or add a key to `extras_require` in setup.py.

**Comment by computron** [comment]
Done via 7d76bb39d4cb09c7b0a4ca9bd5c07c05d9730a6d

Although I am hoping we can get rid of matplotlib entirely at some point and just use some web-based plotting library like Highcharts or Plotly

**Comment by dwinston** [comment]
Thanks!
