### ISSUE TITLE
Sleeping rapidfire works in diamond workflows.

### ISSUE THREAD

**Issue by richardjgowers** [materialsproject/fireworks#233]
So I'm running workflows which occasionally have to join then fork back outwards, so as a trivial example..
```
FW1
V
FW2 FW3
V
FW4
V
FW5 FW6
```
If I run two parallel processes of `rlaunch rapidfire`, then one will do `FW1`, and the other will exit as it sees no job immediately able to run.  The problem being I want the other Worker to stay alive so that `FW2` and `FW3` can be done in parallel.

If I instead do two parallel processes of `rlaunch rapidfire --nlaunches infinite` then both workers will stay alive and perform the workflow as I want, but they will live indefinitely, as once all FWs are done, they will get stuck in a loop of sleeping.

I think what is needed is for `rlaunch rapidfire` to behave more like `rlaunch multi`, in which parallel processes will sleep (and stay alive) if they see that there are future jobs that will appear.  The check which enables this is here:

https://github.com/materialsproject/fireworks/blob/master/fireworks/features/multi_launcher.py#L87

So with `nlaunches=0` (ie until 'completion'), a `rapidfire` Worker should stay alive until it sees that there are no more **future jobs possible** for it to complete.

**Comment by computron** [comment]
Btw, while we are discussing this issue, you can get slightly better behavior by playing with "max_loops" or "timeout" parameters with nlaunches=0.
