### ISSUE TITLE
Most object reprs are unsuitable

### ISSUE THREAD

**Issue by richardjgowers** [materialsproject/fireworks#235]
This is a bit niche, but when I'm doing debugging in ipython the `__repr__` of most Firework objects is awful (ie fills screen with info, crashes things occasionally).

Would it be ok to propose some new reprs for most (Firework, Workflow, Launchpad) objects?

**Comment by computron** [comment]
Sure, that would be great!

**Comment by computron** [comment]
Although do you mean the __str__ method?

https://stackoverflow.com/questions/1436703/difference-between-str-and-repr-in-python

**Comment by computron** [comment]
Actually, do you mean the __str__ method?

https://stackoverflow.com/questions/1436703/difference-between-str-and-repr-in-python

**Comment by computron** [comment]
Closing this, for further discussion please submit to:

https://groups.google.com/forum/#!forum/fireworkflows
