### ISSUE TITLE
Allow Fireworks to reference data held in Workflow

### ISSUE THREAD

**Issue by richardjgowers** [materialsproject/fireworks#236]
I run a lot of workflows where I have a template which I modify for each individual Firework in a Workflow.  This leads to a lot of bloat in the Launchpad (ie the mongodb).

Ideally I'd be allowed to do something like this:
```python
fw1 = fw.Firework([Task1(), Task2()], fw_spec={'template': WorkflowStatic('template')})
fw2 = fw.Firework([Task1(), Task2()], fw_spec={'template': WorkflowStatic('template')})

fw.Workflow([fw1,fw2], statics={'template': [1, 2, 3, 4]})
```
So `template` is defined once in the Workflow, and Fireworks can refer to it in their spec.

In terms of implementing this, after a quick poke around, I think I could do it by changing `Launchpad.get_fw_dict_by_id` to scan for the `WorkflowStatic` objects and replace these with the corresponding document from the Workflow.

So questions..
 - has this been thought of before? (and is it a bad idea?)
 - is it enough to modify `get_fw_dict_by_id` or are there other points that a Firework is accessed?

**Comment by computron** [comment]
Can you submit to:

https://groups.google.com/forum/#!forum/fireworkflows
