### ISSUE TITLE
Fireworks qadapter time format

### ISSUE THREAD

**Issue by shyamd** [materialsproject/fireworks#262]
Fireworks seems to be inconsistent in dealing with time formats in the qadapter

If I used 08:00:00 without quotes for the wall time, it sets the time to 08:00:00 in the submit script, but if I put in 10:00:00, it converts it to 36000, which for most queue systems is taken as the number of minutes of wall time. 

If i put quotes around it, this problem does not arise, but that is something learned via EXTENSIVE trial and error. Mostly error.

**Comment by computron** [comment]
Any idea where this is coming from? I'm pretty sure FWS is just using templating from the YAML read:

fireworks.queue.queue_adapter.QueueAdapterBase#get_script_str

**Comment by shyamd** [comment]
Yup, the problem is with yaml.load
This seems to be a YAML 1.1 vs YAML 1.2 issue.  If you want to keep things 1.1 compliant, it might be nice in the doc to state the timestring has to be in quotes to ensure it gets read in properly.

**Comment by computron** [comment]
I think FWS should probably change to ruamel.yaml like some of the other MP packages, that uses YAML 1.2. Hope to do it sometime soon.
