### ISSUE TITLE
error performing operation move

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/fireworks#323]
Please submit help issues to:
https://groups.google.com/forum/#!forum/fireworkflows

The Github issues is no longer used except for internal development purposes.

If you are unable to use the Google Group, you may submit an issue here, but you must **clearly** state the reason you are unable to use the Google Group in your ticket. Otherwise, your issue will be **closed** without response.

**Comment by computron** [comment]
This issue doesn't provide any details, I am closing it.

**Comment by rkingsbury** [comment]
Apologies @computron . My search opened a new issue without me realizing it.
