### ISSUE TITLE
Show a step progress bar in Django for a workflow

### ISSUE THREAD

**Issue by amard33p** [materialsproject/fireworks#333]
Apologies for posting this here as I tried posting this on Google Groups but it kept getting deleted. We have a web application where user submits a task through Django which creates a workflow using Fireworks. I want to give a visual feedback to the user about the progress of the workflow through a step progress bar like [this](https://i.stack.imgur.com/mTNSr.jpg) where each step is a Firetask. I can do the frontend part quite easily but I am not sure on how I can keep track of the workflow progress constantly.  
Any help will be appreciated. Thanks!

**Comment by shyamd** [comment]
You should be able to load up a `Launchpad` object and use https://github.com/materialsproject/fireworks/blob/1d2585029195896d25e4caace8fa6c653906d2c8/fireworks/core/launchpad.py#L555 to get just the Workflow summary. This should have enough information to implement your progress bar.
