### ISSUE TITLE
qlaunch (non reservation mode) can create too many empty directories

### ISSUE THREAD

**Issue by computron** [materialsproject/fireworks#35]
As mentioned by Shyue, qlaunch rapidfire will create many empty directories that can greatly exceed the number of fireworks in the database. If fireworks are not added to the DB by the time the jobs start running in the queue, you will get empty directories all over your file system.

**Comment by computron** [comment]
This should be fixed by REMOVE_USELESS_DIRS option

**Comment by yuan-gist** [comment]
I installed the latest version of atomate2 and fireworks. When I do `qlaunch rapidfire -m x`, I find that `x` has to be larger than the number of all jobs in the cluster not just my number of jobs. This is not the case for my previous installations
