### ISSUE TITLE
Documentation URL returns a 404 error

### ISSUE THREAD

**Issue by jeffrey-hokanson** [materialsproject/fireworks#433]
Visiting the documentation link in the README.md: "https://materialsproject.github.io/fireworks/" returns a 404 error page from GitHub stating "There isn't a GitHub Pages site here."

**Comment by computron** [comment]
Thank you for alerting us! We recently switched the master branch name to "main" and perhaps the Github Pages got messed up due to this.

@mkhorton @shyamd do you know how to fix?

**Comment by mkhorton** [comment]
I just checked the repo settings, it looked fine. I just refreshed the setting in case and seems to have fixed it?

**Comment by mkhorton** [comment]
Oh, for some reason the https is not working. http://materialsproject.github.io/fireworks works though. Perhaps a GitHub issue?

**Comment by mkhorton** [comment]
Their status page shows everything is ok, but there is this post https://twitter.com/githubstatus/status/1370023050565971980

**Comment by mkhorton** [comment]
FYI, seems to be working now, assume it was a temporary glitch. Closing issue
