### ISSUE TITLE
Documentation suggestion: Explanation of uri_mode: true for a cloud-based MongoDB solution

### ISSUE THREAD

**Issue by arosen93** [materialsproject/fireworks#484]
It took me a while to figure out that if I want to use a URI for a MongoDB, I need to set `uri_mode: true` in the `my_launchpad.yaml` file. This is a bit inconsistent with how `atomate2`/`jobflow`/`maggma` behave.

I think it would be worthwhile to add some information to the documentation about using the `uri_mode: true` flag when trying to access a cloud MongoDB system (e.g. MongoDB Atlas). The appropriate spot would be [here](https://materialsproject.github.io/fireworks/installation.html#testing-connection-to-a-remote-server).

The relevant code is below for context:
https://github.com/materialsproject/fireworks/blob/2cc3b04f9071fe073efb5d9f5c154d95155ba4b5/fireworks/utilities/filepad.py#L73-L86

**Comment by janosh** [comment]
[Related](https://github.com/hackingmaterials/atomate/issues/635#issue-858152525): The atomate docs could also use a bit more guidance for connecting to Atlas.

**Comment by MichaelGoulding** [comment]
The docs say to use uri_store instead of uri_mode
