### ISSUE TITLE
Functionality to pause workflows and better doc for states

### ISSUE THREAD

**Issue by shyuep** [materialsproject/fireworks#58]
I need a way to pause a workflows. For example, my workflows run on weeks at a time. But say I encounter a scheduled maintenance on a resource in the middle of a week. I need a way to tell the workflow to pause after the current FW is done. i.e. any new additions are automatically set to a state called PAUSED until rerun_fws is called.

I am trying to see if current fireworks already allows this. But I am a bit unclear on the meanings behind all the states. Some are obvious (e.g., COMPLETED and RUNNING) but what's the difference between WAITING and READY? A glossary of all these states should be in the doc (and the code).

**Comment by computron** [comment]
Don't think this is happening anytime soon. I'm going to close this, sorry
