### ISSUE TITLE
make style dependencies

### ISSUE THREAD

**Issue by rbaertsch** [materialsproject/fireworks#62]
How would you go about extending the workflow spec to allow make style dependencies? I would be nice to have a general way for the job to be executed only if the inputs have a date that is later than the output files.

This could also be extended to the way you define links in the specs section.

One way would be to write a task specific Firetask but have a general method in the spec would be more useful.

Is this easy to do?

**Comment by computron** [comment]
Closing this issue, as there are no upcoming plans to implement this feature
