### ISSUE TITLE
Task level recovery

### ISSUE THREAD

**Issue by shyuep** [materialsproject/fireworks#63]
I really need task-level recovery for Fireworks. For example, let's say I have a Firework that runs:

Task 1: Setup input
Task 2: Run VASP [Really expensive]
Task 3: Transfer Calc (takes < 1min)
Task 4: Setup new firework (takes seconds)

Let's say for some reason, Transfer Calc fails (e.g., because there was a temporary IO outage). When I rerun the firework, I think the Firework should automatically know that Task 1 and Task 2 have completed successfully and only proceed to do Task 3.

Note that of course I know I can separate every single task into a Firework, but it is just too dumb to wait in the queue just to do a transfer that takes < 1min.

**Comment by computron** [comment]
This feature should be available as of FW v0.97 as implemented by Guido
