### ISSUE TITLE
setting memory for PBS jobs

### ISSUE THREAD

**Issue by matk86** [materialsproject/fireworks#89]
Hi,
I just noticed that the PBS script template doesnt have the variable defined for setting the required process memory.  The line for setting the process memory in PBS looks something like this:
#PBS -l pmem=1000mb

It would be great if you guys could add 'pmem' variable to the PBS template

regards

Kiran Mathew

**Comment by computron** [comment]
Hi Kiran,

Would you be willing to fork the repo, add this tag, and merge back to master? Although this is quick for us to do ourselves, the former method would allow us to document the contribution better.

**Comment by computron** [comment]
I just pulled your request, thanks!
