### ISSUE TITLE
Provide a `kwargs` option for `PyTask`

### ISSUE THREAD

**Issue by jakirkham** [materialsproject/fireworks#95]
In some cases, we may not have the arguments in order or this may not be possible. In these cases, it would be nice to have a `kwargs` argument to allow a dictionary to be passed through and unpacked on the other side.

**Comment by shyuep** [comment]
This is already supported. Any arguments that is not func or starting with a _ is interpreted as a kwargs for the function to be called.

**Comment by jakirkham** [comment]
I see that, but I think have `kwargs` just as `args` is set might be a little cleaner and avoid collisions better.

**Comment by jakirkham** [comment]
Actually, that statement is not correct. If the arguments have an underscore they are **not** included in the forwarded `kwargs` it is everything else that becomes part of `kwargs`. ( https://github.com/materialsproject/fireworks/blob/a2fad1df72a1c9e8c9ef3d984425d39037f71623/fireworks/user_objects/firetasks/script_task.py#L168-L171 )

Regardless, I'm still not thrilled with this as it means if you have a function taking underscored arguments they will be skipped (surprise!). Passing a dictionary is safe in comparison.

If you are concerned with breaking the API, this can be addressed by adding `PyWrapTask` or something similar to implement this behavior.

The only way I knew about this was digging into the code. I think that at a minimum there *should* be some documentation about this ( https://pythonhosted.org/FireWorks/pytask.html?highlight=pytask ).

**Comment by jakirkham** [comment]
I noted the docstring for the `PyTask` object was ignored because `_fw_name` was declared first. As I assume, this order is preferred here, I have simply assigned the docstring to `__doc__`. This should hopefully make up for the missing documentation. This is presented in the PR ( https://github.com/materialsproject/fireworks/pull/94 ).
