### ISSUE TITLE
Improved serialization of arrays

### ISSUE THREAD

**Issue by jakirkham** [materialsproject/fireworks#97]
At present, serialization of NumPy arrays proceeds through conversion to strings. In order to have some way to serialize objects that may not have another strategy, this is an ok fallback. However, it is far from optimal for NumPy arrays. A much better strategy might be to cannibalize ( https://github.com/dattalab/mongowrapper ).

**Comment by shyuep** [comment]
I am not sure this is really the case, but the monty package serailizes numpy very well.

**Comment by jakirkham** [comment]
I see. So, can you help me understand how it is working?  keep finding my arrays are turned into strings when using `PyTask`.

**Comment by jakirkham** [comment]
So, the package pointed to above tries to use GridFS. This would effectively provide a way of chunking on arrays, which is very nice. Particularly, when one wants to work on part of an array. Does monty do this?

**Comment by jakirkham** [comment]
Alternatively, arrays could be serialized to HDF5 and the file path could be saved to the database.

**Comment by computron** [comment]
I don't think monty is meant to automatically handle very large data sets, e.g. GridFS/HDF5. If functioning properly, it should just turn numpy arrays into standard Python lists. If you are seeing conversion to string, that is not the intended behavior. Is it is possible for you to provide a code example that demonstrates what you are seeing? You should have been getting back Python lists.

**Comment by jakirkham** [comment]
> I don't think monty is meant to automatically handle very large data sets, e.g. GridFS/HDF5. If functioning properly, it should just turn numpy arrays into standard Python lists.

Ah ok, thanks for clarifying. At present, I'm writing a variant of PyTask that will handle read/write of NumPy arrays to HDF5 files as a quick workaround. I'm happy to PR this once it is ready if there is interest.

> If you are seeing conversion to string, that is not the intended behavior. Is it is possible for you to provide a code example that demonstrates what you are seeing?

Ok, sure. Let me come up with a simple example to reproduce this.

**Comment by shyuep** [comment]
Monty changes numpy arrays to a dict. Not a list. There is a good reason for that.


Shyue Ping

On May 4, 2015 at 08:58:01, jakirkham (notifications@github.com) wrote:

I don't think monty is meant to automatically handle very large data sets, e.g. GridFS/HDF5. If functioning properly, it should just turn numpy arrays into standard Python lists.

Ah ok, thanks for clarifying. At present, I'm writing a variant of PyTask that will handle read/write of NumPy arrays to HDF5 files as a quick workaround. I'm happy to PR this once it is ready if there is interest.

If you are seeing conversion to string, that is not the intended behavior. Is it is possible for you to provide a code example that demonstrates what you are seeing?

Ok, sure. Let me come up with a simple example to reproduce this.

**Comment by jakirkham** [comment]
Sure, other relevant metadata is preserved, as well. I could be mistaken, but I believe @computron's point was the data in the array itself is converted to a Python list. If that is the case, this is too slow for reasonably sized arrays.

At this point, I have a working implementation of serialization to and from HDF5 using a `PyTask` like object. It is a bit rough, but it is a good starting point, has been tested, and am willing to share.

**Comment by computron** [comment]
Ok it looks like some of this discussion moved into monty, where the proposal (so far) was not accepted.

I would say that I understand the desire to convert numpy arrays into HDF5 for some use cases; however, it seems a bit strange to put it inside FireWorks instead of some other codebase. i.e., let's say numpy or HDF5 changes specifications, it seems strange to have to maintain this conversion functionality in FWS instead of some other code more suited to the specific task (i.e., does h5py meet your needs?) If you think you've done a better job than previous solutions, then maybe it deserves its own repo as converting between numpy/HDF5 is something that people will want to do outside of using FWS. Then FWS will use this as an optional dep.

Let me know what you think and if I'm understanding this correctly.

**Comment by jakirkham** [comment]
Yeah, I decide to raise some of this discussion in `monty` as it is my understanding that it handles more of the serialization aspects of `fireworks` and figured that was a good place to raise this point.

**Comment by jakirkham** [comment]
So, I think something got misinterpreted and maybe it is my fault as I was very terse in my description.

The issue here is efficient serialization of large `numpy` arrays at the boundaries of a task (e.g. a `PyTask`). As far as the serialization itself is concerned, HDF5 via `h5py` does a fantastic job of this. However, the problem as I see it is choosing this conversion path instead of going to a list.

My solution, at present, is a customization of the `PyTask` that handles the serialization at the boundaries (e.g. reading the needed arrays from HDF5 datasets and writing the result to an HDF5 dataset). This works ok and may be useful to others in FWS. It amounts to 38 lines of code and is useless without `fireworks`. In short it is `PyTask` with some extra args to determine what will be expected to be and HDF5 file and handle the serialization via `h5py`.

**Comment by jakirkham** [comment]
However, this strategy gets kind of messy as there are many HDF5 files scattered throughout various launch directories or just dumped in one working directory. So, I'm curious to know if there is a better way to handle this.

**Comment by computron** [comment]
>> In short it is PyTask with some extra args to determine what will be expected to be and HDF5 file and handle the serialization via h5py

Ok, sure, please extend, as long as h5py is imported only in the section of the code right before the conversion happens (so that it is indeed an optional requirement for using PyTask)

Thanks!

**Comment by jakirkham** [comment]
So, I think I have worked out a way to decorate my functions to handle this HDF5 serialization before presenting them to Fireworks so seeing this in Fireworks is no longer necessary.
